### ISSUE TITLE
stale cached file not updated when calling `bfcupdate` with `rid`

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/BiocFileCache#44]
Hi Lori, @lshep 

Sorry, I don't have a great way to reproduce this error without the file. 
I am using the following code to update my resource (attached below):

```r
url <- "https://bioconductor.org/checkResults/3.16/bioc-LATEST/BUILD_STATUS_DB.txt"
bfc <- BiocFileCache()
bquery <- bfcquery(bfc, url, "rname", exact = TRUE)
bfcupdate(bfc, bquery[["rid"]], url)
```
It looks like the method 

https://github.com/Bioconductor/BiocFileCache/blob/3dbe5810c8578771b0e0235ce8eaf1186ccff043/R/BiocFileCache-class.R#L620-L622

has a different signature from the generic: 

https://github.com/Bioconductor/BiocFileCache/blob/3dbe5810c8578771b0e0235ce8eaf1186ccff043/R/BiocFileCache-class.R#L595-L599

which means that the `url` input (with no argument name) does not map to the `rname` in the method as otherwise expected. 
Perhaps it is sufficient to supply only the `bfc` and the `rid` to the method and have the function figure out the `rpath` and `fpath` from e.g., a `bfcquery` as above. 

Otherwise, the code below will not be run because these are `NULL` by default in the method signature: 

https://github.com/Bioconductor/BiocFileCache/blob/3dbe5810c8578771b0e0235ce8eaf1186ccff043/R/BiocFileCache-class.R#L646

https://github.com/Bioconductor/BiocFileCache/blob/3dbe5810c8578771b0e0235ce8eaf1186ccff043/R/BiocFileCache-class.R#L663

Attached file: 

[b1804f2a6090_BUILD_STATUS_DB.txt file](https://github.com/Bioconductor/BiocFileCache/files/10521774/b1804f2a6090_BUILD_STATUS_DB.txt)

Martin @mtmorgan 
Any recommendations on mismatched signatures between the generic and methods?

**Comment by mtmorgan** [comment]
The method needs to have the same named arguments, at the same location, as the generic, so either add `value` to the method

```{r}
setMethod("bfcupdate", "BiocFileCache", 
     function(x, rids, value, rname=NULL, rpath=NULL, fpath=NULL, 
              proxy="", config=list(), ask=TRUE, ...)
```

Or better remove `value` from the signature of the generic (and "missing" method), since `value` is never actually used in any method code?

One could argue that method dispatch is tricky enough to think about without having to get the order of arguments correct, so using named arguments could be encouraged / enforced by moving the `...` before `rname =` in the method signature. Also, it seems like the method should be careful to tell the user if they've given an unused / mis-spelt / etc., argument by checking that `identical(length(list(...)), 0L)`.

**Comment by lshep** [comment]
bfcupdate is for updating information in the database for the resources not to redownload
bfcdownload is to redownload if necessary.
